services:
  backend:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - ./.env.development
      - ./backend/.env.development
    environment:
      - CI=true
      - PNPM_HOME=/pnpm-store
    command: pnpm exec nest start --watch
    volumes:
      - ./:/app
      - ./data:/app/data
      - root_node_modules:/app/node_modules
      - backend_node_modules:/app/backend/node_modules
      - pnpm_global_store:/pnpm-store
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      disable: true

  frontend:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PNPM_HOME=/pnpm-store
    volumes:
      - ./:/app/
      - root_node_modules:/app/node_modules
      - frontend_node_modules:/app/frontend/node_modules
      - pnpm_global_store:/pnpm-store
    depends_on:
      - backend

volumes:
  root_node_modules:
  backend_node_modules:
  frontend_node_modules:
  pnpm_global_store:
