# ==========================================
# 1. ETAP: DEPENDENCIES
# ==========================================
FROM node:22-slim AS deps
WORKDIR /app

# Ustawiamy globalny store pnpm, aby współpracował z naszymi wolumenami
ENV PNPM_HOME="/pnpm-store"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY frontend/package.json ./frontend/package.json
COPY backend/package.json ./backend/package.json
COPY packages/shared/package.json ./packages/shared/package.json
COPY packages/shared/tsconfig.json ./packages/shared/tsconfig.json

RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm rebuild @nestjs/core @swc/core better-sqlite3

COPY packages/shared/src ./packages/shared/src
RUN pnpm --filter shared build

# ==========================================
# 2. ETAP: DEVELOPMENT
# ==========================================
FROM deps AS dev
WORKDIR /app/frontend
EXPOSE 5173
CMD ["pnpm", "dev"]

# ==========================================
# 3. ETAP: BUILD (Tylko do produkcji)
# ==========================================
FROM deps AS build
WORKDIR /app
COPY frontend ./frontend
WORKDIR /app/frontend
RUN pnpm build

# ==========================================
# 4. ETAP: PRODUCTION (Nginx)
# ==========================================
FROM nginx:alpine AS prod
COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
